git add extra/imageviewer/CustomMenu.qml
git add extra/imageviewer/CustomMenuItem.qml
git add extra/imageviewer/MyAnimatedImage.qml
git add extra/imageviewer/MyMenu.qml
git add extra/imageviewer/MySelComp.qml
git add extra/imageviewer/MySelCompMenu.qml
git add extra/imageviewer/MyTextEdit.qml
git add extra/imageviewer/main.py
git add extra/imageviewer/main.qml
git add ffmpeg/gifm.py
git add ffmpeg/libm.py
git add ffmpeg/utilm.py
git add gc/agenda.py
git add gc/alltable.txt
git add gc/chainm.pyw
git add gc/databasem.py
git add gc/dbpushpullm.py
git add gc/seed.py
git add gc/sendmailm.py
git add utillib/companyadd/naukrim.py
git add utillib/requestm.py
git add extra/fix.py
git add extra/modify.py
git add extra/transfer.py
git add ffmpeg/test/ffmpeg_minhinc.py
git add ffmpeg/test/ffmpeg_techawal.py
git add ffmpeg/test/techlogotext.png
git add ffmpeg/test/techlogotext_t.png
git add t.sh
git add utillib/chain.py
git add utillib/data/
git add utillib/databasem.py
git add utillib/databaserequest.py
git add utillib/fetcher.py
git add utillib/google.py
git add utillib/linkedin.py
git add utillib/machinelearningrequest.py
git add utillib/naukri.py
git add utillib/seleniumrequest.py
git add utillib/sendmail.py
git add utillib/util.py
